# Expose management resources in a dedicated port, in order to partition functional and technical endpoints.
management:
  server:
    port: 9090
  # Expose /health/liveness and /health/readiness endpoints for Kubernetes compatibility.
  endpoint:
    health:
      probes:
        enabled: true
  # Expose the following management endpoints:
  #  - prometheus to allow metrics scraping
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  compression:
    enabled: true

spring:
  mvc:
    problemdetails:
      enabled: true

---
# Kubernetes specific configuration
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 15s
server:
  shutdown: graceful
